"""Added Profile Schema, model, and resource

Revision ID: 3899291fd237
Revises: e6468a573c1c
Create Date: 2023-04-27 14:14:14.347536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3899291fd237'
down_revision = 'e6468a573c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=510), nullable=True),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint('group_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['player_id'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('group_ibfk_2', 'user', ['player_id'], ['id'])

    op.drop_table('profile')
    # ### end Alembic commands ###
